find difference between python list and numpy(for HOME WORK)  

Numerical python for fast soliving 

In [2]:
import numpy

In [1]:
print('hi')

hi


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.26.2


In [5]:
l1 = [1, 2, 3, 4, 5]
print(l1)

[1, 2, 3, 4, 5]


In [13]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [15]:
x

array([0.99704218, 0.36478133, 0.46667538, 0.74072111])

In [14]:
x.dtype

dtype('float64')

In [9]:
x= np.array([1, 2, 3, 4, 5])

In [11]:
x=np.random.rand(4)

In [18]:
x=np.random.randint(5,16,10)
x

array([ 7, 14, 11, 14,  7,  7, 11, 10, 15,  7])

In [19]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
y = np.random.randint(3,4, (3,4))
y

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [23]:
z=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
z

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a=np.ones(((5,5)),dtype="int")

In [34]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
a=np.zeros(((5,5)),dtype="int")

In [36]:
a


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
a=np.full((5,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [39]:
a=np.eye(5,5,dtype ="int")
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [40]:
a=7*np.eye(5,5,dtype ="int")
a

array([[7, 0, 0, 0, 0],
       [0, 7, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 7]])

In [41]:
a.dtype

dtype('int32')

In [42]:
a.shape

(5, 5)

In [43]:
a.size

25

In [44]:
x.size

10

In [45]:
z.ndim

3

In [46]:
z.shape

(2, 3, 3)

In [47]:
y.shape

(3, 4)

In [48]:
print(x)

[ 7 14 11 14  7  7 11 10 15  7]


In [62]:
# x = np.array([3, 5, 7, 2, 8])

In [63]:
x.min

<function ndarray.min>

In [59]:
x.max

<function ndarray.max>

In [61]:
x.mean

<function ndarray.mean>

In [60]:
x.mean()

5.0

In [66]:
#create 2d array of (3,3)
x = np.array([[3, 5, 7], [2, 8, 10], [6, 4, 12]])
x

array([[ 3,  5,  7],
       [ 2,  8, 10],
       [ 6,  4, 12]])

array([[ 3,  5,  7],
       [ 2,  8, 10],
       [ 6,  4, 12]])

indexing is the process of accessing a single element form a sequence using its positon or index.
it retrives a single elment at a specific positions.
python uses zero-based indexing (0 is the first element)
negative indexing allows acess from the end of the structure

In [82]:
g = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,   13, 14, 15, 16])
g

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

slicing: extracts a sublist (portion) of elements with in specififed range.

In [72]:
g[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [73]:
g[2:10]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
# g[:]=100

In [81]:
g


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100])

In [91]:
np.flip(g)

array([[ 3,  5,  7],
       [ 2,  8, 10],
       [ 6,  4, 12]])

In [92]:
g


array([[12,  4,  6],
       [10,  8,  2],
       [ 7,  5,  3]])

                                        TUTORIAL - 0
                        
1. TensorFlow

Description:
TensorFlow is an open-source library developed by Google for building and training machine learning and deep learning models.

Use Cases:

Image recognition

Speech recognition

Neural networks

Predictive analytics

Natural Language Processing

Key Features:

Supports deep learning and machine learning

Works on CPU, GPU, and TPU

Used for large-scale applications

Has tools for model training and deployment

2. PyTorch

Description:
PyTorch is an open-source deep learning framework developed by Facebook. It is widely used in research and AI development.

Use Cases:

Deep learning research

Computer vision

NLP (Natural Language Processing)

Neural networks

Key Features:

Easy to learn and use

Dynamic computation graphs

Strong support for GPUs

Preferred by AI researchers

3. Keras

Description:
Keras is a high-level deep learning library that runs on top of TensorFlow and makes neural network creation simple.

Use Cases:

Image processing

Text classification

Deep learning model building

Key Features:

Simple and user-friendly

Fast model building

Supports CNN and RNN

Works with TensorFlow backend

4. OpenCV

Description:
OpenCV is an open-source computer vision library used for processing images and videos.

Use Cases:

Face detection

Object tracking

Image recognition

Video processing

Key Features:

Supports real-time image processing

Works with Python, C++, Java

Large collection of vision algorithms

5. Scikit-Learn

Description:
Scikit-Learn is a Python library used for machine learning tasks like classification, regression, and clustering.

Use Cases:

Data analysis

Prediction systems

Spam detection

Recommendation systems

Key Features:

Easy to use

Supports many ML algorithms

Works well with NumPy and Pandas

6. NLTK (Natural Language Toolkit)

Description:
NLTK is a Python library used for working with human language data.

Use Cases:

Text processing

Chatbots

Sentiment analysis

Speech and text understanding

Key Features:

Tokenization and stemming

Word tagging

Language models

Large collection of datasets

7. SpaCy

Description:
SpaCy is an advanced NLP library designed for real-world applications.

Use Cases:

Text classification

Named entity recognition

Chatbots

Document analysis

Key Features:

Fast and efficient

Supports deep learning

Pre-trained models

Easy integration

8. GPT-3 (OpenAI)

Description:
GPT-3 is a powerful AI model that can understand and generate human-like text.

Use Cases:

Chatbots

Content writing

Code generation

Language translation

Key Features:

Trained on massive data

Generates human-like text

Supports many languages

Can answer questions

9. IBM Watson

Description:
IBM Watson is an AI platform that provides tools for data analysis, NLP, and machine learning.

Use Cases:

Chatbots

Business analytics

Healthcare systems

Customer support

Key Features:

Cloud-based AI services

NLP and speech recognition

Data visualization tools

10. RapidMiner

Description:
RapidMiner is a data science platform used for data mining and machine learning.

Use Cases:

Business data analysis

Predictive analytics

Fraud detection

Key Features:

No-code/low-code platform

Drag-and-drop interface

Supports ML algorithms

In [ ]:
## TUTORIAL 2
