                                            TUTORIAL - 1

In [8]:
import numpy

In [9]:
import numpy as np

In [10]:
import random

In [2]:
arr = [10, 20, 30, 40, 50]
arr

[10, 20, 30, 40, 50]

In [7]:
arr1 = np.random.rand(5)
arr1

array([0.77065221, 0.32420978, 0.85332747, 0.92711035, 0.53892501])

In [16]:
arr2 = np.random.uniform(5, 15, 10)
print(arr2)

[ 6.60800965 12.72061841 10.91799321 11.36520516  5.33137572 10.04842743
 11.8632221  11.72116427 14.92313475 11.03417266]


In [21]:
# Create 2D array - 4 by 3 size.
arr3 = np.random.rand(4, 3,)
print(arr3)

[[0.01907395 0.31917198 0.01377135]
 [0.07204364 0.95403158 0.58868502]
 [0.91654556 0.4070514  0.57345536]
 [0.71118506 0.40355804 0.09349685]]


In [24]:
# Create 2D array with size 3 by 3. Elements values are random number(by default values between 0 to 1)
arr4 = np.random.rand(3,3)
print(arr4)

[[0.57277191 0.47585103 0.07657975]
 [0.79155237 0.88201482 0.33778047]
 [0.57727755 0.07549233 0.83757891]]


In [26]:
# Generate random value from range 5 to 15 with 2D array size 3 by 3.
arr5 = np.random.uniform(5, 15, (3,3))
print(arr5)

[[ 6.23260432  9.6606008  14.78169435]
 [14.09048054  9.48710976 13.94846396]
 [ 9.37756824  9.75616796 14.37707123]]


In [28]:
# Create 3D array with size 2 * 3 * 2.
arr = np.random.rand(2, 3, 2)
print(arr)

[[[0.21140081 0.82318829]
  [0.71784237 0.16440452]
  [0.69503561 0.18104015]]

 [[0.81821665 0.87216608]
  [0.95454842 0.61682921]
  [0.89207278 0.05786874]]]


In [29]:
# Initialize 5 by 5 array with all values are zeros.
arr_zeros = np.zeros((5, 5))
print(arr_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# Find out shape of array.
shape = arr_zeros.shape
print(shape)

(5, 5)


In [14]:
# Find dimension of array.
arr_zeros = np.zeros((5, 5))
dimension = arr_zeros.ndim
print(dimension)

2


In [15]:
# Find no. of elements of from above any array.
# Find no. of elements of from above any array.
num_elements = arr_zeros.size
print(num_elements)

25


In [17]:
# Print Reverse the array.
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])    

[5 4 3 2 1]


In [19]:
# Extract elements from index 1 to 7 with a step of 2.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:7:2])   

[2 4 6]


In [20]:
# Reassign value 100 to all elements.
arr = np.array([1, 2, 3, 4, 5])
arr.fill(100)
print(arr)

[100 100 100 100 100]


In [21]:
# Reassign value for particular index.

arr = np.array([1, 2, 3, 4, 5])
arr[2] = 100
print(arr)  

[  1   2 100   4   5]
