In [1]:
import numpy as np

In [36]:
# 1 - d arrray
arr = np.array([1,2,3])
print(arr)
print(arr[2])

[1 2 3]
3


In [43]:
# 2 - d arrray
arr = np.array([[1,2,3],[2,4,5]])
print(arr)
print(arr[1,2])

[[1 2 3]
 [2 4 5]]
5


In [46]:
# 3 - d arrray
arr = np.array([[[1,2,3],[2,4,2],[12,3,4]]])
print(arr)
print(f'{arr[0,2,1]}')


[[[ 1  2  3]
  [ 2  4  2]
  [12  3  4]]]
3


In [51]:
rand = np.random.rand(6)
print(rand)

[0.30413654 0.60614421 0.71541687 0.30205544 0.82805201 0.62764405]


In [72]:
rand = np.random.randint(3)
print(rand)

1


In [78]:
arr = np.array([[1,2,3],[12,3,4],[3,5,3]])
print(arr)

[[ 1  2  3]
 [12  3  4]
 [ 3  5  3]]


In [81]:
a = np.random.randint(3,10,(3,3))
print(a)

[[5 9 4]
 [4 8 7]
 [5 3 8]]


In [84]:
arr = np.array([[1,2,3],[3,2,1],[1,2,3]])
arr

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3]])

In [96]:
arr = np.zeros((4,4) ,dtype=int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [98]:
arr = np.ones((5,5),dtype=int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [102]:
arr = np.full ((6,6),6)
arr

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [104]:
arr = np.eye(5,5, dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [106]:
arr = 5*np.eye(5,5,dtype=int)
arr

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

In [107]:
arr.dtype

dtype('int64')

In [108]:
arr.size

25

In [111]:
arr.ndim

2

In [112]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.ndim)   # number of dimensions
print(arr.shape)  # rows and columns
print(arr.size)   # total elements

2
(2, 3)
6


In [117]:
print(np.arange(1,11,2))

[1 3 5 7 9]


In [142]:
arr = np.arange(1,17)
rs = arr.reshape(4,4)
rs

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [120]:
arr = np.arange(1,10)

print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [126]:
np.random.rand(3,3)

array([[7.00864624e-01, 4.95926306e-02, 2.73437305e-01],
       [4.20097742e-01, 3.48521579e-01, 5.90205734e-04],
       [3.04290087e-01, 4.37042823e-01, 9.91873416e-01]])

In [127]:
arr = np.array([5,10,15,20,25])

In [128]:
arr = np.zeros((3,3),dtype=int)

In [145]:
arr = np.arange(1,20,2)
print(arr)
print(np.std(arr))

[ 1  3  5  7  9 11 13 15 17 19]
5.744562646538029


In [143]:
ar = np.array([1,2,3,4,5,6])
ar.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
print(arr.T)


[ 1  3  5  7  9 11 13 15 17 19]


## Pandas

In [148]:
import pandas as pd

In [155]:
s1 = pd.series([1,2,3],  index=['a','b','c'])


AttributeError: module 'pandas' has no attribute 'series'